//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongKham3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Prescription
    {
        public int ID { get; set; }
        public string IdStaff { get; set; }
        public int IDCustomer { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> DateOfCreate { get; set; }
        public int IDMedicine { get; set; }
        public int Count { get; set; }
        public string Dosage { get; set; }
        public string Symptom { get; set; }
        public string Using { get; set; }
        public string Status { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Medicine Medicine { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
